# Generated by Django 4.0.6 on 2023-07-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
    ]
