# Generated by Django 4.0.6 on 2023-07-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmodals', '0004_rename_is_accepted_registration_is_payed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
